name: Deployment application

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 'cfy-k8s-lab/sandbox1'
          token: ${{ secrets.PAT_TOKEN }}
          path: 'deployment-repo'

      - name: Update ArgoCD Application manifest
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd deployment-repo

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          touch application.yaml
          echo "apiVersion: argoproj.io/v1alpha1" >> application.yaml
          echo "kind: Application" >> application.yaml
          echo "metadata:" >> application.yaml
          echo "  name: my-app" >> application.yaml
          git checkout -b deploy-${{ github.sha }}
          git add application.yaml
          git commit --allow-empty -m "Deployment application ${{ github.sha }}"
          git push origin deploy-${{ github.sha }}

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run:
          cd deployment-repo

          curl -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/cfy-k8s-lab/sandbox1/pulls \
            -d '{
              "title": "Deploy new version of application",
              "body": "Updating ArgoCD Application manifest",
              "head": "deploy-${{ github.sha }}",
              "base": "env/sit",
              "labels": ["automated-pr"]
            }'