name: Deployment application

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 'cfy-k8s-lab/sandbox1'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'deployment-repo'

      - name: Update ArgoCD Application manifest
        run: |
          cd deployment-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b deploy-${{ github.sha }}
          git commit -m "Deployment application ${{ github.sha }}"
          git push origin deploy-${{ github.sha }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'cfy-k8s-lab/sandbox1'
          title: 'Deploy new version of application'
          body: 'Updating ArgoCD Application manifest'
          branch: deploy-${{ github.sha }}
          base: 'env/sit'
          labels: 'automated-pr'
